name: tdmpc2
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pytorch
  - torchvision
  - cudatoolkit=11.7
  - glew
  - glib
  - setuptools=65.5.0
  - wheel<0.40.0
  - pip==21
  - pip:
    - absl-py
    - glfw
    - kornia
    - termcolor
    - gym==0.21.0
    - moviepy
    - ffmpeg
    - imageio
    - imageio-ffmpeg
    - omegaconf
    - hydra-core
    - hydra-submitit-launcher
    - submitit
    - pandas
    - patchelf
    - protobuf
    - tqdm
    - "cython<3"
    - dm-control
    - pillow
    - tensordict-nightly
    - torchrl-nightly
    - wandb
